spring:
  application:
    name: db-service-vuelo
    
server:
  port: 8081

eureka:
   client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
   instance:
    hostname: localhost
      